apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admission-role
  namespace: heimdall
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admission-role-binding
  namespace: heimdall
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admission-role
subjects:
  - kind: ServiceAccount
    name: default
