name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Semantic version tag for the release'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push tag
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kryanbeane/heimdall-admission:${{ github.event.inputs.tag }}
      - name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kryanbeane/heimdall-admission:latest

  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false